name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: Build package
    environment: Production
    timeout-minutes: 15
    runs-on: ${{ matrix.os }}
    env:
      AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
      AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
      AUTH0_TOKEN_AUDIENCE: ${{ secrets.AUTH0_TOKEN_AUDIENCE }}
      SALABLE_API_ENDPOINT: ${{ secrets.SALABLE_API_ENDPOINT }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x.x

      - name: Install dependencies
        run: npm ci

      - name: Build package
        run: npm run build
