name: Release

on:
  push:
    branches:
      - main
      - beta
      - alpha
      - "*.*.*"
      - "*.*"

jobs:
  release:
    name: Release
    concurrency: release
    environment: Production
    runs-on: ubuntu-latest
    env:
      AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
      AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
      AUTH0_TOKEN_AUDIENCE: ${{ secrets.AUTH0_TOKEN_AUDIENCE }}
      SALABLE_API_ENDPOINT: ${{ secrets.SALABLE_API_ENDPOINT }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "lts/*"
      - name: Install dependencies
        run: HUSKY=0 npm install
      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
